### ISSUE TITLE
测试异常：Debian 11.6 amd64，内核  5.10.0-20-amd64  5.10.158-2 (2022-12-13) 运行异常

### ISSUE THREAD

**Issue by now2roll** [gadore/ink-screen-bluetooth#1]
非常好的开发设计创意！
我也有同一款设备，当时买来是放在车上当号码牌用的。但是用店家提供的 安卓 APP，操作起来烦琐，另外做出的号码数字相当粗糙，
完全没有体现 墨水屏 的精细效果。

我在 Debian 11.6 amd64 系统，
* 内核：Linux debian 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
安装了 yarnpkg 软件包（系统没有 yarn 软件包），运行时报错，无法正常连接。

操作过程：

下载、解压，再

cd /home/user/下载/ink-screen-bluetooth-main/

* 再运行 yarnpkg
输出内容（运行时间持续约60秒）

```
yarn install v1.22.10
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[3/4] ⠐ @abandonware/bluetooth-hci-socket
[2/4] ⠐ canvas
[-/4] ⠐ waiting...
error /home/user/下载/ink-screen-bluetooth-main/node_modules/@abandonware/bluetooth-hci-socket: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments: 
Directory: /home/user/下载/ink-screen-bluetooth-main/node_modules/@abandonware/bluetooth-hci-socket
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@12.22.12 | linux | x64
node-pre-gyp http GET https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v72-linux-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for @abandonware/bluetooth-hci-socket@0.5.3-10 and node@12.22.12 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v72-linux-x64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/下载/ink-screen-bluetooth-main/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:83:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:470:16)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
node-pre-gyp ERR! System Linux 5.10.0-20-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/home/user/下载/ink-screen-bluetooth-main/node_modules/@abandonware/bluetooth-hci-socket/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
node-pre-gyp ERR! cwd /home/user/下载/ink-screen-bluetooth-main/node_modules/@abandonware/bluetooth-hci-socket
node-pre-gyp ERR! node -v v12.22.12
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
```

再打开第2个终端，切换到目录

 `cd /home/user/下载/ink-screen-bluetooth-main/`

运行 node app.js

输出：
 
```
/home/user2/下载/ink-screen-bluetooth-main/app.js:148
            currentDevice?.disconnect()
                          ^

SyntaxError: Unexpected token '.'` yarnpkg 
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

问题出在哪里？是内核版本不一致，还是必须使用 yarn 的同名软件包？

**Comment by gadore** [comment]
这个是 bluetooth-hci-socket 包的依赖中需要用到node-gyp，可以到这两个仓库中去看下安装要求，有对主流OS安装进行说明的

**Comment by now2roll** [comment]
非常感谢回复！个人对蓝牙硬件协议，树莓派不是太熟悉。
再说一些个人在 Debian 11.6 amd64 笔记本电脑上的运行状态：
1. 按你的提示，apt install 安装了 yarnpkg, node-gyp, node-pre-gyp 这几个软件包.
2. 顺便也安装了 bluez-hcidump 这个包。
3. 在 https://github.com/noble/node-bluetooth-hci-socket 找到了  bluetooth-hci-socket  相关包。但还没有安装。个人再试试。
